# Generated by Django 5.1.1 on 2025-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0042_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, default='Your College Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_registered',
            field=models.ManyToManyField(blank=True, null=True, to='Donotechapp.courseitem'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, default='Department', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='student@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_semester',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='0', max_length=17, null=True),
        ),
    ]
